# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgis
  encoding: unicode
  database: myapp_development
  pool: 5
  postgis_extension: postgis
  schema_search_path: public,postgis

test:
  adapter: postgis
  encoding: unicode
  database: myapp_test
  pool: 5
  postgis_extension: postgis
  schema_search_path: public,postgis

production:
  adapter: postgis
  encoding: unicode
  database: pg_production
  url: <%= ENV.fetch('DATABASE_URL', '').sub(/^postgres/, "postgis") %>
  pool: 5
  postgis_extension: postgis
  schema_search_path: public,postgis
